---
name: Tests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 . --count --show-source --statistics

  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: ["2.11", "2.10", 2.9, 2.9-py2, 2.8]
      fail-fast: true

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Run all tests
      run: |
        PYTHON=`which python3 || which python`
        $PYTHON ckanext/csrf_filter/test_anti_csrf.py

