---
name: Tests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 . --count --show-source --statistics

  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: ["2.11", "2.10", 2.9]
        experimental: [false]
        include:
          - ckan-version: "master"
            experimental: true  # master is unstable, good to know if we are compatible or not
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-version }}
      options: --user root

    steps:
    - uses: actions/checkout@v4
      continue-on-error: ${{ matrix.experimental }}

    - name: Pin setuptools for ckan 2.9 only
      if: ${{ matrix.ckan-version == 2.9 }}
      run: pip install "setuptools>=44.1.0,<71"
      continue-on-error: ${{ matrix.experimental }}

    - name: Install requirements
      continue-on-error: ${{ matrix.experimental }}
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Run all tests
      continue-on-error: ${{ matrix.experimental }}
      run: |
        PYTHON=`which python3 || which python`
        $PYTHON ckanext/csrf_filter/test_anti_csrf.py

    - name: Test Summary
      uses: test-summary/action@v2
      continue-on-error: ${{ matrix.experimental }}
      with:
        paths: "/tmp/artifacts/junit/*.xml"
      if: always()
